/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2pbo2021;

import com.formdev.flatlaf.*;
import javax.swing.UIManager;
/**
 *
 * @author haqiz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Mobil mobil = new Mobil();
    
    public Main() {
        FlatDarkLaf.install();
        UIManager.put( "TabbedPane.tabSeparatorsFullHeight", true );
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        tpMain = new javax.swing.JTabbedPane();
        pnlForm = new javax.swing.JPanel();
        lblMerk = new javax.swing.JLabel();
        lblPlat = new javax.swing.JLabel();
        lblWarna = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        tfMerk = new javax.swing.JTextField();
        tfPlat = new javax.swing.JTextField();
        tfWarna = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        pnlInfo = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpMain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpMainFocusGained(evt);
            }
        });
        tpMain.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tpMainComponentShown(evt);
            }
        });

        pnlForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlFormFocusGained(evt);
            }
        });

        lblMerk.setText("Merk");

        lblPlat.setText("Plat");

        lblWarna.setText("Warna");

        lblJenis.setText("Jenis");

        tfMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMerkActionPerformed(evt);
            }
        });

        tfWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWarnaActionPerformed(evt);
            }
        });

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truck" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWarna)
                    .addComponent(lblMerk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJenis, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfWarna, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPlat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfMerk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbJenis, 0, 303, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnSubmit)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMerk)
                    .addComponent(tfMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlat))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWarna)
                    .addComponent(tfWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenis)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        tpMain.addTab("Form", pnlForm);

        pnlTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlTableFocusGained(evt);
            }
        });
        pnlTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlTableComponentShown(evt);
            }
        });

        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Merk", "Plat", "Warna", "Jenis"
            }
        ));
        jScrollPane1.setViewportView(tblMobil);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        tpMain.addTab("Table", pnlTable);

        lblNama.setText("Nama : Muhammad Izzatul Haq");

        lblNIM.setText("NIM : 1904618");

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foto.jpg"))); // NOI18N
        lblFoto.setText("jLabel3");
        lblFoto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblFotoComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNIM)
                    .addComponent(lblNama))
                .addGap(231, 231, 231))
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNama)
                .addGap(18, 18, 18)
                .addComponent(lblNIM)
                .addGap(18, 18, 18)
                .addComponent(lblFoto)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        tpMain.addTab("Info", pnlInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpMainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpMainFocusGained

    }//GEN-LAST:event_tpMainFocusGained

    private void tfMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMerkActionPerformed

    private void tfWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWarnaActionPerformed

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String merk = tfMerk.getText();
        String plat = tfPlat.getText();
        String warna = tfWarna.getText();
        String jenis = cmbJenis.getSelectedItem().toString();
        
        mobil.createMobil(merk, plat, warna, jenis);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void pnlTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlTableFocusGained
        
    }//GEN-LAST:event_pnlTableFocusGained

    private void pnlFormFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlFormFocusGained
        
    }//GEN-LAST:event_pnlFormFocusGained

    private void tpMainComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tpMainComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tpMainComponentShown

    private void pnlTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlTableComponentShown
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMobil.getModel();
        
        //Hapus dulu row jika ada
        if(model.getRowCount() > 0){
            for(int i = model.getRowCount() -1 ; i >= 0; i--){
                model.removeRow(i);
            }
        }
        
        Object[][] data = mobil.getMobils();
        
        for (Object[] data1 : data) {
            model.addRow(data1);
        }
    }//GEN-LAST:event_pnlTableComponentShown

    private void lblFotoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblFotoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFotoComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPlat;
    private javax.swing.JLabel lblWarna;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblMobil;
    private javax.swing.JTextField tfMerk;
    private javax.swing.JTextField tfPlat;
    private javax.swing.JTextField tfWarna;
    private javax.swing.JTabbedPane tpMain;
    // End of variables declaration//GEN-END:variables
}
